name: "Mike Koch"
description: "Mike Koch's Website"
email: "mkoch227@gmail.com"

url: "http://mikekoch.me"

collections:
  - my_projects
  - my_contributions

tabs:
  - title: My Projects
    id: my-projects
  - title: About
    id: about
  - title: Contact
    id: contact

# Social networks usernames ("name" is used to obtain the proper FontAwesome icon)
social:
  - name: twitter
    url: https://www.twitter.com/mkoch227
    tooltip-text: "Follow me on Twitter"
  - name: github
    url: https://www.github.com/mkoch227
    tooltip-text: "Follow me on GitHub"
    
footer:
    copyright: Michael Koch
    social: Follow Me
    
# Site colors (excluding # sign)
colors:
    primary: 18bc9c
    secondary: 2c3e50
    tertiary: 233140